### ISSUE TITLE
Error when trying to use Domino API inside Java Agent

### ISSUE THREAD

**Issue by EmpireElement** [OpenNTF/org.openntf.domino#142]
I get the following error when trying to use the API inside a Java Agent:

java.lang.IllegalStateException: org.openntf.domino.utils.Factory is not initialized for this thread!
    at org.openntf.domino.utils.Factory.getThreadVariables(Factory.java:345)
    at org.openntf.domino.utils.Factory.getWrapperFactory(Factory.java:627)
    at org.openntf.domino.AgentBase.getSession(AgentBase.java:25)
    at JavaAgent.NotesMain(Unknown Source)
    at lotus.domino.AgentBase.runNotes(Unknown Source)
    at lotus.domino.NotesThread.run(Unknown Source)

**Comment by leader80** [comment]
Same problem here!

**Comment by jesse-gallagher** [comment]
Further discussion is on https://github.com/OpenNTF/org.openntf.domino/issues/162
