### ISSUE TITLE
toJSON failing for non-US date timezones

### ISSUE THREAD

**Issue by paulswithers** [OpenNTF/org.openntf.domino#168]
HTTP JVM: java.time.format.DateTimeParseException: Text ‘2019-02-14 10:29:13’ could not be parsed at index 2
HTTP JVM:  at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1960)
HTTP JVM:  at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1862)
HTTP JVM:  at java.time.ZonedDateTime.parse(ZonedDateTime.java:608)
HTTP JVM:  at org.openntf.domino.impl.DateTime.toGMTDateTime(DateTime.java:474)

**Comment by paulswithers** [comment]
Fixed in 10.0.1
