### ISSUE TITLE
DXL exporter operation failed

### ISSUE THREAD

**Issue by sblaylock** [OpenNTF/org.openntf.domino#187]
### Please include the following:
- [12.0.2 ] Domino server version (relevant for runtime issues)
- [12.0.2a ] ODA version

We upgraded from the 12.0.2  Domino api to the 12.0.2a version in the Update Site on the server and we started to see the following issues:

NotesException: DXL exporter operation failed
at lotus.domino.local.DxlExporter.exportDxl(Unknown Source)
at org.openntf.domino.impl.DxlExporter.exportDxl(DxlExporter.java:57)
at org.openntf.domino.impl.Database.isDesignProtected(Database.java:1067)
at org.openntf.domino.impl.Database.getDesign(Database.java:1083)
at org.openntf.domino.impl.Database.readDesignNote(Database.java:3787)
at org.openntf.domino.impl.Database.isLargeSummaryEnabled(Database.java:3767)
at org.openntf.domino.utils.TypeUtils.writeToItem(TypeUtils.java:2072)
at org.openntf.domino.impl.Document.replaceItemValueLotus(Document.java:2969)
at org.openntf.domino.impl.Document.replaceItemValue(Document.java:2878)
at org.openntf.domino.impl.Document.replaceItemValue(Document.java:2821)

The designer was also updated and the application was "cleaned" with the 12.0.2a version. Once we dropped back to the 12.0.2 version everything was fine.

**Comment by radimjager** [comment]
Jsem mimo kancelář do 21.06.2023.

Na vaši zprávu odpovím, jakmile se vrátím. V případě nutnosti se obraťe, prosím, na Ing. Radku Bezděkovskou nebo Mgr. Erika Borše. 


Poznámka: Toto je automatická odpověď na vaši zprávu  "[OpenNTF/org.openntf.domino] DXL exporter operation failed (Issue #187)"( odeslanou dne 06.06.2023 18:40:15) . 

Toto je jediné oznámení, které obdržíte v době nepřítomnosti této osoby.

**Comment by sblaylock** [comment]
Has any progress been made on this issue?

**Comment by jesse-gallagher** [comment]
I've modified the check to skip the part where it'd need to do a DXL export. I can't say for sure that it'll fix it, but maybe it will.

[org.openntf.domino.updatesite-12.0.3-SNAPSHOT.zip](https://github.com/OpenNTF/org.openntf.domino/files/13688863/org.openntf.domino.updatesite-12.0.3-SNAPSHOT.zip)

**Comment by sblaylock** [comment]
Thanks Jesse.

    On Friday, December 15, 2023 at 10:57:47 AM PST, Jesse Gallagher ***@***.***> wrote:  
 
 


I've modified the check to skip the part where it'd need to do a DXL export. I can't say for sure that it'll fix it, but maybe it will.

org.openntf.domino.updatesite-12.0.3-SNAPSHOT.zip
